-- Dữ liệu phường/xã hành chính mới (34 tỉnh/thành, 2025)
-- Nguồn: github.com/ThangLeQuoc/vietnamese-provinces-database

DELETE FROM phuong_xa WHERE id >= 0;

INSERT INTO phuong_xa (ma_xa, ten_xa, loai_xa, ten_xa_ngan, ma_tinh, ten_tinh) VALUES
  ('00004', 'Phường Ba Đình', 'phường', 'Ba Đình', '01', 'Thành phố Hà Nội'),
  ('00008', 'Phường Ngọc Hà', 'phường', 'Ngọc Hà', '01', 'Thành phố Hà Nội'),
  ('00025', 'Phường Giảng Võ', 'phường', 'Giảng Võ', '01', 'Thành phố Hà Nội'),
  ('00070', 'Phường Hoàn Kiếm', 'phường', 'Hoàn Kiếm', '01', 'Thành phố Hà Nội'),
  ('00082', 'Phường Cửa Nam', 'phường', 'Cửa Nam', '01', 'Thành phố Hà Nội'),
  ('00091', 'Phường Phú Thượng', 'phường', 'Phú Thượng', '01', 'Thành phố Hà Nội'),
  ('00097', 'Phường Hồng Hà', 'phường', 'Hồng Hà', '01', 'Thành phố Hà Nội'),
  ('00103', 'Phường Tây Hồ', 'phường', 'Tây Hồ', '01', 'Thành phố Hà Nội'),
  ('00118', 'Phường Bồ Đề', 'phường', 'Bồ Đề', '01', 'Thành phố Hà Nội'),
  ('00127', 'Phường Việt Hưng', 'phường', 'Việt Hưng', '01', 'Thành phố Hà Nội'),
  ('00136', 'Phường Phúc Lợi', 'phường', 'Phúc Lợi', '01', 'Thành phố Hà Nội'),
  ('00145', 'Phường Long Biên', 'phường', 'Long Biên', '01', 'Thành phố Hà Nội'),
  ('00160', 'Phường Nghĩa Đô', 'phường', 'Nghĩa Đô', '01', 'Thành phố Hà Nội'),
  ('00166', 'Phường Cầu Giấy', 'phường', 'Cầu Giấy', '01', 'Thành phố Hà Nội'),
  ('00175', 'Phường Yên Hoà', 'phường', 'Yên Hoà', '01', 'Thành phố Hà Nội'),
  ('00190', 'Phường Ô Chợ Dừa', 'phường', 'Ô Chợ Dừa', '01', 'Thành phố Hà Nội'),
  ('00199', 'Phường Láng', 'phường', 'Láng', '01', 'Thành phố Hà Nội'),
  ('00226', 'Phường Văn Miếu - Quốc Tử Giám', 'phường', 'Văn Miếu - Quốc Tử Giám', '01', 'Thành phố Hà Nội'),
  ('00229', 'Phường Kim Liên', 'phường', 'Kim Liên', '01', 'Thành phố Hà Nội'),
  ('00235', 'Phường Đống Đa', 'phường', 'Đống Đa', '01', 'Thành phố Hà Nội'),
  ('00256', 'Phường Hai Bà Trưng', 'phường', 'Hai Bà Trưng', '01', 'Thành phố Hà Nội'),
  ('00283', 'Phường Vĩnh Tuy', 'phường', 'Vĩnh Tuy', '01', 'Thành phố Hà Nội'),
  ('00292', 'Phường Bạch Mai', 'phường', 'Bạch Mai', '01', 'Thành phố Hà Nội'),
  ('00301', 'Phường Vĩnh Hưng', 'phường', 'Vĩnh Hưng', '01', 'Thành phố Hà Nội'),
  ('00316', 'Phường Định Công', 'phường', 'Định Công', '01', 'Thành phố Hà Nội'),
  ('00322', 'Phường Tương Mai', 'phường', 'Tương Mai', '01', 'Thành phố Hà Nội'),
  ('00328', 'Phường Lĩnh Nam', 'phường', 'Lĩnh Nam', '01', 'Thành phố Hà Nội'),
  ('00331', 'Phường Hoàng Mai', 'phường', 'Hoàng Mai', '01', 'Thành phố Hà Nội'),
  ('00337', 'Phường Hoàng Liệt', 'phường', 'Hoàng Liệt', '01', 'Thành phố Hà Nội'),
  ('00340', 'Phường Yên Sở', 'phường', 'Yên Sở', '01', 'Thành phố Hà Nội'),
  ('00352', 'Phường Phương Liệt', 'phường', 'Phương Liệt', '01', 'Thành phố Hà Nội'),
  ('00364', 'Phường Khương Đình', 'phường', 'Khương Đình', '01', 'Thành phố Hà Nội'),
  ('00367', 'Phường Thanh Xuân', 'phường', 'Thanh Xuân', '01', 'Thành phố Hà Nội'),
  ('00376', 'Xã Sóc Sơn', 'xã', 'Sóc Sơn', '01', 'Thành phố Hà Nội'),
  ('00382', 'Xã Kim Anh', 'xã', 'Kim Anh', '01', 'Thành phố Hà Nội'),
  ('00385', 'Xã Trung Giã', 'xã', 'Trung Giã', '01', 'Thành phố Hà Nội'),
  ('00430', 'Xã Đa Phúc', 'xã', 'Đa Phúc', '01', 'Thành phố Hà Nội'),
  ('00433', 'Xã Nội Bài', 'xã', 'Nội Bài', '01', 'Thành phố Hà Nội'),
  ('00454', 'Xã Đông Anh', 'xã', 'Đông Anh', '01', 'Thành phố Hà Nội'),
  ('00466', 'Xã Phúc Thịnh', 'xã', 'Phúc Thịnh', '01', 'Thành phố Hà Nội'),
  ('00475', 'Xã Thư Lâm', 'xã', 'Thư Lâm', '01', 'Thành phố Hà Nội'),
  ('00493', 'Xã Thiên Lộc', 'xã', 'Thiên Lộc', '01', 'Thành phố Hà Nội'),
  ('00508', 'Xã Vĩnh Thanh', 'xã', 'Vĩnh Thanh', '01', 'Thành phố Hà Nội'),
  ('00541', 'Xã Phù Đổng', 'xã', 'Phù Đổng', '01', 'Thành phố Hà Nội'),
  ('00562', 'Xã Thuận An', 'xã', 'Thuận An', '01', 'Thành phố Hà Nội'),
  ('00565', 'Xã Gia Lâm', 'xã', 'Gia Lâm', '01', 'Thành phố Hà Nội'),
  ('00577', 'Xã Bát Tràng', 'xã', 'Bát Tràng', '01', 'Thành phố Hà Nội'),
  ('00592', 'Phường Từ Liêm', 'phường', 'Từ Liêm', '01', 'Thành phố Hà Nội'),
  ('00598', 'Phường Thượng Cát', 'phường', 'Thượng Cát', '01', 'Thành phố Hà Nội'),
  ('00602', 'Phường Đông Ngạc', 'phường', 'Đông Ngạc', '01', 'Thành phố Hà Nội'),
  ('00611', 'Phường Xuân Đỉnh', 'phường', 'Xuân Đỉnh', '01', 'Thành phố Hà Nội'),
  ('00613', 'Phường Tây Tựu', 'phường', 'Tây Tựu', '01', 'Thành phố Hà Nội'),
  ('00619', 'Phường Phú Diễn', 'phường', 'Phú Diễn', '01', 'Thành phố Hà Nội'),
  ('00622', 'Phường Xuân Phương', 'phường', 'Xuân Phương', '01', 'Thành phố Hà Nội'),
  ('00634', 'Phường Tây Mỗ', 'phường', 'Tây Mỗ', '01', 'Thành phố Hà Nội'),
  ('00637', 'Phường Đại Mỗ', 'phường', 'Đại Mỗ', '01', 'Thành phố Hà Nội'),
  ('00640', 'Xã Thanh Trì', 'xã', 'Thanh Trì', '01', 'Thành phố Hà Nội'),
  ('00643', 'Phường Thanh Liệt', 'phường', 'Thanh Liệt', '01', 'Thành phố Hà Nội'),
  ('00664', 'Xã Đại Thanh', 'xã', 'Đại Thanh', '01', 'Thành phố Hà Nội'),
  ('00679', 'Xã Ngọc Hồi', 'xã', 'Ngọc Hồi', '01', 'Thành phố Hà Nội'),
  ('00685', 'Xã Nam Phù', 'xã', 'Nam Phù', '01', 'Thành phố Hà Nội'),
  ('04930', 'Xã Yên Xuân', 'xã', 'Yên Xuân', '01', 'Thành phố Hà Nội'),
  ('08974', 'Xã Quang Minh', 'xã', 'Quang Minh', '01', 'Thành phố Hà Nội'),
  ('08980', 'Xã Yên Lãng', 'xã', 'Yên Lãng', '01', 'Thành phố Hà Nội'),
  ('08995', 'Xã Tiến Thắng', 'xã', 'Tiến Thắng', '01', 'Thành phố Hà Nội'),
  ('09022', 'Xã Mê Linh', 'xã', 'Mê Linh', '01', 'Thành phố Hà Nội'),
  ('09552', 'Phường Kiến Hưng', 'phường', 'Kiến Hưng', '01', 'Thành phố Hà Nội'),
  ('09556', 'Phường Hà Đông', 'phường', 'Hà Đông', '01', 'Thành phố Hà Nội'),
  ('09562', 'Phường Yên Nghĩa', 'phường', 'Yên Nghĩa', '01', 'Thành phố Hà Nội'),
  ('09568', 'Phường Phú Lương', 'phường', 'Phú Lương', '01', 'Thành phố Hà Nội'),
  ('09574', 'Phường Sơn Tây', 'phường', 'Sơn Tây', '01', 'Thành phố Hà Nội'),
  ('09604', 'Phường Tùng Thiện', 'phường', 'Tùng Thiện', '01', 'Thành phố Hà Nội'),
  ('09616', 'Xã Đoài Phương', 'xã', 'Đoài Phương', '01', 'Thành phố Hà Nội'),
  ('09619', 'Xã Quảng Oai', 'xã', 'Quảng Oai', '01', 'Thành phố Hà Nội'),
  ('09634', 'Xã Cổ Đô', 'xã', 'Cổ Đô', '01', 'Thành phố Hà Nội'),
  ('09661', 'Xã Minh Châu', 'xã', 'Minh Châu', '01', 'Thành phố Hà Nội'),
  ('09664', 'Xã Vật Lại', 'xã', 'Vật Lại', '01', 'Thành phố Hà Nội'),
  ('09676', 'Xã Bất Bạt', 'xã', 'Bất Bạt', '01', 'Thành phố Hà Nội'),
  ('09694', 'Xã Suối Hai', 'xã', 'Suối Hai', '01', 'Thành phố Hà Nội'),
  ('09700', 'Xã Ba Vì', 'xã', 'Ba Vì', '01', 'Thành phố Hà Nội'),
  ('09706', 'Xã Yên Bài', 'xã', 'Yên Bài', '01', 'Thành phố Hà Nội'),
  ('09715', 'Xã Phúc Thọ', 'xã', 'Phúc Thọ', '01', 'Thành phố Hà Nội'),
  ('09739', 'Xã Phúc Lộc', 'xã', 'Phúc Lộc', '01', 'Thành phố Hà Nội'),
  ('09772', 'Xã Hát Môn', 'xã', 'Hát Môn', '01', 'Thành phố Hà Nội'),
  ('09784', 'Xã Đan Phượng', 'xã', 'Đan Phượng', '01', 'Thành phố Hà Nội'),
  ('09787', 'Xã Liên Minh', 'xã', 'Liên Minh', '01', 'Thành phố Hà Nội'),
  ('09817', 'Xã Ô Diên', 'xã', 'Ô Diên', '01', 'Thành phố Hà Nội'),
  ('09832', 'Xã Hoài Đức', 'xã', 'Hoài Đức', '01', 'Thành phố Hà Nội'),
  ('09856', 'Xã Dương Hoà', 'xã', 'Dương Hoà', '01', 'Thành phố Hà Nội'),
  ('09871', 'Xã Sơn Đồng', 'xã', 'Sơn Đồng', '01', 'Thành phố Hà Nội'),
  ('09877', 'Xã An Khánh', 'xã', 'An Khánh', '01', 'Thành phố Hà Nội'),
  ('09886', 'Phường Dương Nội', 'phường', 'Dương Nội', '01', 'Thành phố Hà Nội'),
  ('09895', 'Xã Quốc Oai', 'xã', 'Quốc Oai', '01', 'Thành phố Hà Nội'),
  ('09910', 'Xã Kiều Phú', 'xã', 'Kiều Phú', '01', 'Thành phố Hà Nội'),
  ('09931', 'Xã Hưng Đạo', 'xã', 'Hưng Đạo', '01', 'Thành phố Hà Nội'),
  ('09952', 'Xã Phú Cát', 'xã', 'Phú Cát', '01', 'Thành phố Hà Nội'),
  ('09955', 'Xã Thạch Thất', 'xã', 'Thạch Thất', '01', 'Thành phố Hà Nội'),
  ('09982', 'Xã Hạ Bằng', 'xã', 'Hạ Bằng', '01', 'Thành phố Hà Nội'),
  ('09988', 'Xã Hoà Lạc', 'xã', 'Hoà Lạc', '01', 'Thành phố Hà Nội'),
  ('10003', 'Xã Tây Phương', 'xã', 'Tây Phương', '01', 'Thành phố Hà Nội'),
  ('10015', 'Phường Chương Mỹ', 'phường', 'Chương Mỹ', '01', 'Thành phố Hà Nội'),
  ('10030', 'Xã Phú Nghĩa', 'xã', 'Phú Nghĩa', '01', 'Thành phố Hà Nội'),
  ('10045', 'Xã Xuân Mai', 'xã', 'Xuân Mai', '01', 'Thành phố Hà Nội'),
  ('10072', 'Xã Quảng Bị', 'xã', 'Quảng Bị', '01', 'Thành phố Hà Nội'),
  ('10081', 'Xã Trần Phú', 'xã', 'Trần Phú', '01', 'Thành phố Hà Nội'),
  ('10096', 'Xã Hoà Phú', 'xã', 'Hoà Phú', '01', 'Thành phố Hà Nội'),
  ('10114', 'Xã Thanh Oai', 'xã', 'Thanh Oai', '01', 'Thành phố Hà Nội'),
  ('10126', 'Xã Bình Minh', 'xã', 'Bình Minh', '01', 'Thành phố Hà Nội'),
  ('10144', 'Xã Tam Hưng', 'xã', 'Tam Hưng', '01', 'Thành phố Hà Nội'),
  ('10180', 'Xã Dân Hoà', 'xã', 'Dân Hoà', '01', 'Thành phố Hà Nội'),
  ('10183', 'Xã Thường Tín', 'xã', 'Thường Tín', '01', 'Thành phố Hà Nội'),
  ('10210', 'Xã Hồng Vân', 'xã', 'Hồng Vân', '01', 'Thành phố Hà Nội'),
  ('10231', 'Xã Thượng Phúc', 'xã', 'Thượng Phúc', '01', 'Thành phố Hà Nội'),
  ('10237', 'Xã Chương Dương', 'xã', 'Chương Dương', '01', 'Thành phố Hà Nội'),
  ('10273', 'Xã Phú Xuyên', 'xã', 'Phú Xuyên', '01', 'Thành phố Hà Nội'),
  ('10279', 'Xã Phượng Dực', 'xã', 'Phượng Dực', '01', 'Thành phố Hà Nội'),
  ('10330', 'Xã Chuyên Mỹ', 'xã', 'Chuyên Mỹ', '01', 'Thành phố Hà Nội'),
  ('10342', 'Xã Đại Xuyên', 'xã', 'Đại Xuyên', '01', 'Thành phố Hà Nội'),
  ('10354', 'Xã Vân Đình', 'xã', 'Vân Đình', '01', 'Thành phố Hà Nội'),
  ('10369', 'Xã Ứng Thiên', 'xã', 'Ứng Thiên', '01', 'Thành phố Hà Nội'),
  ('10402', 'Xã Ứng Hoà', 'xã', 'Ứng Hoà', '01', 'Thành phố Hà Nội'),
  ('10417', 'Xã Hoà Xá', 'xã', 'Hoà Xá', '01', 'Thành phố Hà Nội'),
  ('10441', 'Xã Mỹ Đức', 'xã', 'Mỹ Đức', '01', 'Thành phố Hà Nội'),
  ('10459', 'Xã Phúc Sơn', 'xã', 'Phúc Sơn', '01', 'Thành phố Hà Nội'),
  ('10465', 'Xã Hồng Sơn', 'xã', 'Hồng Sơn', '01', 'Thành phố Hà Nội'),
  ('10489', 'Xã Hương Sơn', 'xã', 'Hương Sơn', '01', 'Thành phố Hà Nội'),
  ('01840', 'Phường Đức Xuân', 'phường', 'Đức Xuân', '19', 'Tỉnh Thái Nguyên'),
  ('01843', 'Phường Bắc Kạn', 'phường', 'Bắc Kạn', '19', 'Tỉnh Thái Nguyên'),
  ('01849', 'Xã Phong Quang', 'xã', 'Phong Quang', '19', 'Tỉnh Thái Nguyên'),
  ('01864', 'Xã Bằng Thành', 'xã', 'Bằng Thành', '19', 'Tỉnh Thái Nguyên'),
  ('01879', 'Xã Cao Minh', 'xã', 'Cao Minh', '19', 'Tỉnh Thái Nguyên'),
  ('01882', 'Xã Nghiên Loan', 'xã', 'Nghiên Loan', '19', 'Tỉnh Thái Nguyên'),
  ('01894', 'Xã Phúc Lộc', 'xã', 'Phúc Lộc', '19', 'Tỉnh Thái Nguyên'),
  ('01906', 'Xã Ba Bể', 'xã', 'Ba Bể', '19', 'Tỉnh Thái Nguyên'),
  ('01912', 'Xã Chợ Rã', 'xã', 'Chợ Rã', '19', 'Tỉnh Thái Nguyên'),
  ('01921', 'Xã Thượng Minh', 'xã', 'Thượng Minh', '19', 'Tỉnh Thái Nguyên'),
  ('01933', 'Xã Đồng Phúc', 'xã', 'Đồng Phúc', '19', 'Tỉnh Thái Nguyên'),
  ('01936', 'Xã Nà Phặc', 'xã', 'Nà Phặc', '19', 'Tỉnh Thái Nguyên'),
  ('01942', 'Xã Bằng Vân', 'xã', 'Bằng Vân', '19', 'Tỉnh Thái Nguyên'),
  ('01954', 'Xã Ngân Sơn', 'xã', 'Ngân Sơn', '19', 'Tỉnh Thái Nguyên'),
  ('01957', 'Xã Thượng Quan', 'xã', 'Thượng Quan', '19', 'Tỉnh Thái Nguyên'),
  ('01960', 'Xã Hiệp Lực', 'xã', 'Hiệp Lực', '19', 'Tỉnh Thái Nguyên'),
  ('01969', 'Xã Phủ Thông', 'xã', 'Phủ Thông', '19', 'Tỉnh Thái Nguyên'),
  ('01981', 'Xã Vĩnh Thông', 'xã', 'Vĩnh Thông', '19', 'Tỉnh Thái Nguyên'),
  ('02008', 'Xã Cẩm Giàng', 'xã', 'Cẩm Giàng', '19', 'Tỉnh Thái Nguyên'),
  ('02014', 'Xã Bạch Thông', 'xã', 'Bạch Thông', '19', 'Tỉnh Thái Nguyên'),
  ('02020', 'Xã Chợ Đồn', 'xã', 'Chợ Đồn', '19', 'Tỉnh Thái Nguyên'),
  ('02026', 'Xã Nam Cường', 'xã', 'Nam Cường', '19', 'Tỉnh Thái Nguyên'),
  ('02038', 'Xã Quảng Bạch', 'xã', 'Quảng Bạch', '19', 'Tỉnh Thái Nguyên'),
  ('02044', 'Xã Yên Thịnh', 'xã', 'Yên Thịnh', '19', 'Tỉnh Thái Nguyên'),
  ('02071', 'Xã Nghĩa Tá', 'xã', 'Nghĩa Tá', '19', 'Tỉnh Thái Nguyên'),
  ('02083', 'Xã Yên Phong', 'xã', 'Yên Phong', '19', 'Tỉnh Thái Nguyên'),
  ('02086', 'Xã Chợ Mới', 'xã', 'Chợ Mới', '19', 'Tỉnh Thái Nguyên'),
  ('02101', 'Xã Thanh Mai', 'xã', 'Thanh Mai', '19', 'Tỉnh Thái Nguyên'),
  ('02104', 'Xã Tân Kỳ', 'xã', 'Tân Kỳ', '19', 'Tỉnh Thái Nguyên'),
  ('02107', 'Xã Thanh Thịnh', 'xã', 'Thanh Thịnh', '19', 'Tỉnh Thái Nguyên'),
  ('02116', 'Xã Yên Bình', 'xã', 'Yên Bình', '19', 'Tỉnh Thái Nguyên'),
  ('02143', 'Xã Văn Lang', 'xã', 'Văn Lang', '19', 'Tỉnh Thái Nguyên'),
  ('02152', 'Xã Cường Lợi', 'xã', 'Cường Lợi', '19', 'Tỉnh Thái Nguyên'),
  ('02155', 'Xã Na Rì', 'xã', 'Na Rì', '19', 'Tỉnh Thái Nguyên'),
  ('02176', 'Xã Trần Phú', 'xã', 'Trần Phú', '19', 'Tỉnh Thái Nguyên'),
  ('02185', 'Xã Côn Minh', 'xã', 'Côn Minh', '19', 'Tỉnh Thái Nguyên'),
  ('02191', 'Xã Xuân Dương', 'xã', 'Xuân Dương', '19', 'Tỉnh Thái Nguyên'),
  ('05443', 'Phường Phan Đình Phùng', 'phường', 'Phan Đình Phùng', '19', 'Tỉnh Thái Nguyên'),
  ('05455', 'Phường Quyết Thắng', 'phường', 'Quyết Thắng', '19', 'Tỉnh Thái Nguyên'),
  ('05467', 'Phường Gia Sàng', 'phường', 'Gia Sàng', '19', 'Tỉnh Thái Nguyên'),
  ('05482', 'Phường Quan Triều', 'phường', 'Quan Triều', '19', 'Tỉnh Thái Nguyên'),
  ('05488', 'Xã Đại Phúc', 'xã', 'Đại Phúc', '19', 'Tỉnh Thái Nguyên'),
  ('05500', 'Phường Tích Lương', 'phường', 'Tích Lương', '19', 'Tỉnh Thái Nguyên'),
  ('05503', 'Xã Tân Cương', 'xã', 'Tân Cương', '19', 'Tỉnh Thái Nguyên'),
  ('05518', 'Phường Sông Công', 'phường', 'Sông Công', '19', 'Tỉnh Thái Nguyên'),
  ('05528', 'Phường Bách Quang', 'phường', 'Bách Quang', '19', 'Tỉnh Thái Nguyên'),
  ('05533', 'Phường Bá Xuyên', 'phường', 'Bá Xuyên', '19', 'Tỉnh Thái Nguyên'),
  ('05542', 'Xã Lam Vỹ', 'xã', 'Lam Vỹ', '19', 'Tỉnh Thái Nguyên'),
  ('05551', 'Xã Kim Phượng', 'xã', 'Kim Phượng', '19', 'Tỉnh Thái Nguyên'),
  ('05563', 'Xã Phượng Tiến', 'xã', 'Phượng Tiến', '19', 'Tỉnh Thái Nguyên'),
  ('05569', 'Xã Định Hoá', 'xã', 'Định Hoá', '19', 'Tỉnh Thái Nguyên'),
  ('05581', 'Xã Trung Hội', 'xã', 'Trung Hội', '19', 'Tỉnh Thái Nguyên'),
  ('05587', 'Xã Bình Yên', 'xã', 'Bình Yên', '19', 'Tỉnh Thái Nguyên'),
  ('05602', 'Xã Phú Đình', 'xã', 'Phú Đình', '19', 'Tỉnh Thái Nguyên'),
  ('05605', 'Xã Bình Thành', 'xã', 'Bình Thành', '19', 'Tỉnh Thái Nguyên'),
  ('05611', 'Xã Phú Lương', 'xã', 'Phú Lương', '19', 'Tỉnh Thái Nguyên'),
  ('05620', 'Xã Yên Trạch', 'xã', 'Yên Trạch', '19', 'Tỉnh Thái Nguyên'),
  ('05632', 'Xã Hợp Thành', 'xã', 'Hợp Thành', '19', 'Tỉnh Thái Nguyên'),
  ('05641', 'Xã Vô Tranh', 'xã', 'Vô Tranh', '19', 'Tỉnh Thái Nguyên'),
  ('05662', 'Xã Trại Cau', 'xã', 'Trại Cau', '19', 'Tỉnh Thái Nguyên'),
  ('05665', 'Xã Văn Lăng', 'xã', 'Văn Lăng', '19', 'Tỉnh Thái Nguyên'),
  ('05674', 'Xã Quang Sơn', 'xã', 'Quang Sơn', '19', 'Tỉnh Thái Nguyên'),
  ('05680', 'Xã Văn Hán', 'xã', 'Văn Hán', '19', 'Tỉnh Thái Nguyên'),
  ('05692', 'Xã Đồng Hỷ', 'xã', 'Đồng Hỷ', '19', 'Tỉnh Thái Nguyên'),
  ('05707', 'Xã Nam Hoà', 'xã', 'Nam Hoà', '19', 'Tỉnh Thái Nguyên'),
  ('05710', 'Phường Linh Sơn', 'phường', 'Linh Sơn', '19', 'Tỉnh Thái Nguyên'),
  ('05716', 'Xã Võ Nhai', 'xã', 'Võ Nhai', '19', 'Tỉnh Thái Nguyên'),
  ('05719', 'Xã Sảng Mộc', 'xã', 'Sảng Mộc', '19', 'Tỉnh Thái Nguyên'),
  ('05722', 'Xã Nghinh Tường', 'xã', 'Nghinh Tường', '19', 'Tỉnh Thái Nguyên'),
  ('05725', 'Xã Thần Sa', 'xã', 'Thần Sa', '19', 'Tỉnh Thái Nguyên'),
  ('05740', 'Xã La Hiên', 'xã', 'La Hiên', '19', 'Tỉnh Thái Nguyên'),
  ('05746', 'Xã Tràng Xá', 'xã', 'Tràng Xá', '19', 'Tỉnh Thái Nguyên'),
  ('05755', 'Xã Dân Tiến', 'xã', 'Dân Tiến', '19', 'Tỉnh Thái Nguyên'),
  ('05773', 'Xã Phú Xuyên', 'xã', 'Phú Xuyên', '19', 'Tỉnh Thái Nguyên'),
  ('05776', 'Xã Đức Lương', 'xã', 'Đức Lương', '19', 'Tỉnh Thái Nguyên'),
  ('05788', 'Xã Phú Lạc', 'xã', 'Phú Lạc', '19', 'Tỉnh Thái Nguyên'),
  ('05800', 'Xã Phú Thịnh', 'xã', 'Phú Thịnh', '19', 'Tỉnh Thái Nguyên'),
  ('05809', 'Xã An Khánh', 'xã', 'An Khánh', '19', 'Tỉnh Thái Nguyên'),
  ('05818', 'Xã La Bằng', 'xã', 'La Bằng', '19', 'Tỉnh Thái Nguyên'),
  ('05830', 'Xã Đại Từ', 'xã', 'Đại Từ', '19', 'Tỉnh Thái Nguyên'),
  ('05845', 'Xã Vạn Phú', 'xã', 'Vạn Phú', '19', 'Tỉnh Thái Nguyên'),
  ('05851', 'Xã Quân Chu', 'xã', 'Quân Chu', '19', 'Tỉnh Thái Nguyên'),
  ('05857', 'Phường Phúc Thuận', 'phường', 'Phúc Thuận', '19', 'Tỉnh Thái Nguyên'),
  ('05860', 'Phường Phổ Yên', 'phường', 'Phổ Yên', '19', 'Tỉnh Thái Nguyên'),
  ('05881', 'Xã Thành Công', 'xã', 'Thành Công', '19', 'Tỉnh Thái Nguyên'),
  ('05890', 'Phường Vạn Xuân', 'phường', 'Vạn Xuân', '19', 'Tỉnh Thái Nguyên'),
  ('05899', 'Phường Trung Thành', 'phường', 'Trung Thành', '19', 'Tỉnh Thái Nguyên'),
  ('05908', 'Xã Phú Bình', 'xã', 'Phú Bình', '19', 'Tỉnh Thái Nguyên'),
  ('05917', 'Xã Tân Khánh', 'xã', 'Tân Khánh', '19', 'Tỉnh Thái Nguyên'),
  ('05923', 'Xã Tân Thành', 'xã', 'Tân Thành', '19', 'Tỉnh Thái Nguyên'),
  ('05941', 'Xã Điềm Thuỵ', 'xã', 'Điềm Thuỵ', '19', 'Tỉnh Thái Nguyên'),
  ('05953', 'Xã Kha Sơn', 'xã', 'Kha Sơn', '19', 'Tỉnh Thái Nguyên'),
  ('07210', 'Phường Bắc Giang', 'phường', 'Bắc Giang', '24', 'Tỉnh Bắc Ninh'),
  ('07228', 'Phường Đa Mai', 'phường', 'Đa Mai', '24', 'Tỉnh Bắc Ninh'),
  ('07246', 'Xã Xuân Lương', 'xã', 'Xuân Lương', '24', 'Tỉnh Bắc Ninh'),
  ('07264', 'Xã Tam Tiến', 'xã', 'Tam Tiến', '24', 'Tỉnh Bắc Ninh'),
  ('07282', 'Xã Đồng Kỳ', 'xã', 'Đồng Kỳ', '24', 'Tỉnh Bắc Ninh'),
  ('07288', 'Xã Yên Thế', 'xã', 'Yên Thế', '24', 'Tỉnh Bắc Ninh'),
  ('07294', 'Xã Bố Hạ', 'xã', 'Bố Hạ', '24', 'Tỉnh Bắc Ninh'),
  ('07306', 'Xã Nhã Nam', 'xã', 'Nhã Nam', '24', 'Tỉnh Bắc Ninh'),
  ('07330', 'Xã Phúc Hoà', 'xã', 'Phúc Hoà', '24', 'Tỉnh Bắc Ninh'),
  ('07333', 'Xã Quang Trung', 'xã', 'Quang Trung', '24', 'Tỉnh Bắc Ninh'),
  ('07339', 'Xã Tân Yên', 'xã', 'Tân Yên', '24', 'Tỉnh Bắc Ninh'),
  ('07351', 'Xã Ngọc Thiện', 'xã', 'Ngọc Thiện', '24', 'Tỉnh Bắc Ninh'),
  ('07375', 'Xã Lạng Giang', 'xã', 'Lạng Giang', '24', 'Tỉnh Bắc Ninh'),
  ('07381', 'Xã Tiên Lục', 'xã', 'Tiên Lục', '24', 'Tỉnh Bắc Ninh'),
  ('07399', 'Xã Kép', 'xã', 'Kép', '24', 'Tỉnh Bắc Ninh'),
  ('07420', 'Xã Mỹ Thái', 'xã', 'Mỹ Thái', '24', 'Tỉnh Bắc Ninh'),
  ('07432', 'Xã Tân Dĩnh', 'xã', 'Tân Dĩnh', '24', 'Tỉnh Bắc Ninh'),
  ('07444', 'Xã Lục Nam', 'xã', 'Lục Nam', '24', 'Tỉnh Bắc Ninh'),
  ('07450', 'Xã Đông Phú', 'xã', 'Đông Phú', '24', 'Tỉnh Bắc Ninh'),
  ('07462', 'Xã Bảo Đài', 'xã', 'Bảo Đài', '24', 'Tỉnh Bắc Ninh'),
  ('07486', 'Xã Nghĩa Phương', 'xã', 'Nghĩa Phương', '24', 'Tỉnh Bắc Ninh'),
  ('07489', 'Xã Trường Sơn', 'xã', 'Trường Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07492', 'Xã Lục Sơn', 'xã', 'Lục Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07498', 'Xã Bắc Lũng', 'xã', 'Bắc Lũng', '24', 'Tỉnh Bắc Ninh'),
  ('07519', 'Xã Cẩm Lý', 'xã', 'Cẩm Lý', '24', 'Tỉnh Bắc Ninh'),
  ('07525', 'Phường Chũ', 'phường', 'Chũ', '24', 'Tỉnh Bắc Ninh'),
  ('07531', 'Xã Tân Sơn', 'xã', 'Tân Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07534', 'Xã Sa Lý', 'xã', 'Sa Lý', '24', 'Tỉnh Bắc Ninh'),
  ('07537', 'Xã Biên Sơn', 'xã', 'Biên Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07543', 'Xã Sơn Hải', 'xã', 'Sơn Hải', '24', 'Tỉnh Bắc Ninh'),
  ('07552', 'Xã Kiên Lao', 'xã', 'Kiên Lao', '24', 'Tỉnh Bắc Ninh'),
  ('07573', 'Xã Biển Động', 'xã', 'Biển Động', '24', 'Tỉnh Bắc Ninh'),
  ('07582', 'Xã Lục Ngạn', 'xã', 'Lục Ngạn', '24', 'Tỉnh Bắc Ninh'),
  ('07594', 'Xã Đèo Gia', 'xã', 'Đèo Gia', '24', 'Tỉnh Bắc Ninh'),
  ('07603', 'Xã Nam Dương', 'xã', 'Nam Dương', '24', 'Tỉnh Bắc Ninh'),
  ('07612', 'Phường Phượng Sơn', 'phường', 'Phượng Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07615', 'Xã Sơn Động', 'xã', 'Sơn Động', '24', 'Tỉnh Bắc Ninh'),
  ('07616', 'Xã Tây Yên Tử', 'xã', 'Tây Yên Tử', '24', 'Tỉnh Bắc Ninh'),
  ('07621', 'Xã Vân Sơn', 'xã', 'Vân Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07627', 'Xã Đại Sơn', 'xã', 'Đại Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('07642', 'Xã Yên Định', 'xã', 'Yên Định', '24', 'Tỉnh Bắc Ninh'),
  ('07654', 'Xã An Lạc', 'xã', 'An Lạc', '24', 'Tỉnh Bắc Ninh'),
  ('07663', 'Xã Tuấn Đạo', 'xã', 'Tuấn Đạo', '24', 'Tỉnh Bắc Ninh'),
  ('07672', 'Xã Dương Hưu', 'xã', 'Dương Hưu', '24', 'Tỉnh Bắc Ninh'),
  ('07681', 'Phường Yên Dũng', 'phường', 'Yên Dũng', '24', 'Tỉnh Bắc Ninh'),
  ('07682', 'Phường Tân An', 'phường', 'Tân An', '24', 'Tỉnh Bắc Ninh'),
  ('07696', 'Phường Tiền Phong', 'phường', 'Tiền Phong', '24', 'Tỉnh Bắc Ninh'),
  ('07699', 'Phường Tân Tiến', 'phường', 'Tân Tiến', '24', 'Tỉnh Bắc Ninh'),
  ('07735', 'Xã Đồng Việt', 'xã', 'Đồng Việt', '24', 'Tỉnh Bắc Ninh'),
  ('07738', 'Phường Cảnh Thuỵ', 'phường', 'Cảnh Thuỵ', '24', 'Tỉnh Bắc Ninh'),
  ('07774', 'Phường Tự Lạn', 'phường', 'Tự Lạn', '24', 'Tỉnh Bắc Ninh'),
  ('07777', 'Phường Việt Yên', 'phường', 'Việt Yên', '24', 'Tỉnh Bắc Ninh'),
  ('07795', 'Phường Nếnh', 'phường', 'Nếnh', '24', 'Tỉnh Bắc Ninh'),
  ('07798', 'Phường Vân Hà', 'phường', 'Vân Hà', '24', 'Tỉnh Bắc Ninh'),
  ('07822', 'Xã Hoàng Vân', 'xã', 'Hoàng Vân', '24', 'Tỉnh Bắc Ninh'),
  ('07840', 'Xã Hiệp Hoà', 'xã', 'Hiệp Hoà', '24', 'Tỉnh Bắc Ninh'),
  ('07864', 'Xã Hợp Thịnh', 'xã', 'Hợp Thịnh', '24', 'Tỉnh Bắc Ninh'),
  ('07870', 'Xã Xuân Cẩm', 'xã', 'Xuân Cẩm', '24', 'Tỉnh Bắc Ninh'),
  ('09169', 'Phường Vũ Ninh', 'phường', 'Vũ Ninh', '24', 'Tỉnh Bắc Ninh'),
  ('09187', 'Phường Kinh Bắc', 'phường', 'Kinh Bắc', '24', 'Tỉnh Bắc Ninh'),
  ('09190', 'Phường Võ Cường', 'phường', 'Võ Cường', '24', 'Tỉnh Bắc Ninh'),
  ('09193', 'Xã Yên Phong', 'xã', 'Yên Phong', '24', 'Tỉnh Bắc Ninh'),
  ('09202', 'Xã Tam Giang', 'xã', 'Tam Giang', '24', 'Tỉnh Bắc Ninh'),
  ('09205', 'Xã Yên Trung', 'xã', 'Yên Trung', '24', 'Tỉnh Bắc Ninh'),
  ('09208', 'Xã Tam Đa', 'xã', 'Tam Đa', '24', 'Tỉnh Bắc Ninh'),
  ('09238', 'Xã Văn Môn', 'xã', 'Văn Môn', '24', 'Tỉnh Bắc Ninh'),
  ('09247', 'Phường Quế Võ', 'phường', 'Quế Võ', '24', 'Tỉnh Bắc Ninh'),
  ('09253', 'Phường Nhân Hoà', 'phường', 'Nhân Hoà', '24', 'Tỉnh Bắc Ninh'),
  ('09265', 'Phường Phương Liễu', 'phường', 'Phương Liễu', '24', 'Tỉnh Bắc Ninh'),
  ('09286', 'Phường Nam Sơn', 'phường', 'Nam Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('09292', 'Xã Phù Lãng', 'xã', 'Phù Lãng', '24', 'Tỉnh Bắc Ninh'),
  ('09295', 'Phường Bồng Lai', 'phường', 'Bồng Lai', '24', 'Tỉnh Bắc Ninh'),
  ('09301', 'Phường Đào Viên', 'phường', 'Đào Viên', '24', 'Tỉnh Bắc Ninh'),
  ('09313', 'Xã Chi Lăng', 'xã', 'Chi Lăng', '24', 'Tỉnh Bắc Ninh'),
  ('09319', 'Xã Tiên Du', 'xã', 'Tiên Du', '24', 'Tỉnh Bắc Ninh'),
  ('09325', 'Phường Hạp Lĩnh', 'phường', 'Hạp Lĩnh', '24', 'Tỉnh Bắc Ninh'),
  ('09334', 'Xã Liên Bão', 'xã', 'Liên Bão', '24', 'Tỉnh Bắc Ninh'),
  ('09340', 'Xã Đại Đồng', 'xã', 'Đại Đồng', '24', 'Tỉnh Bắc Ninh'),
  ('09343', 'Xã Tân Chi', 'xã', 'Tân Chi', '24', 'Tỉnh Bắc Ninh'),
  ('09349', 'Xã Phật Tích', 'xã', 'Phật Tích', '24', 'Tỉnh Bắc Ninh'),
  ('09367', 'Phường Từ Sơn', 'phường', 'Từ Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('09370', 'Phường Tam Sơn', 'phường', 'Tam Sơn', '24', 'Tỉnh Bắc Ninh'),
  ('09379', 'Phường Phù Khê', 'phường', 'Phù Khê', '24', 'Tỉnh Bắc Ninh'),
  ('09385', 'Phường Đồng Nguyên', 'phường', 'Đồng Nguyên', '24', 'Tỉnh Bắc Ninh'),
  ('09400', 'Phường Thuận Thành', 'phường', 'Thuận Thành', '24', 'Tỉnh Bắc Ninh'),
  ('09409', 'Phường Mão Điền', 'phường', 'Mão Điền', '24', 'Tỉnh Bắc Ninh'),
  ('09427', 'Phường Trí Quả', 'phường', 'Trí Quả', '24', 'Tỉnh Bắc Ninh'),
  ('09430', 'Phường Trạm Lộ', 'phường', 'Trạm Lộ', '24', 'Tỉnh Bắc Ninh'),
  ('09433', 'Phường Song Liễu', 'phường', 'Song Liễu', '24', 'Tỉnh Bắc Ninh'),
  ('09445', 'Phường Ninh Xá', 'phường', 'Ninh Xá', '24', 'Tỉnh Bắc Ninh'),
  ('09454', 'Xã Gia Bình', 'xã', 'Gia Bình', '24', 'Tỉnh Bắc Ninh'),
  ('09466', 'Xã Cao Đức', 'xã', 'Cao Đức', '24', 'Tỉnh Bắc Ninh'),
  ('09469', 'Xã Đại Lai', 'xã', 'Đại Lai', '24', 'Tỉnh Bắc Ninh'),
  ('09475', 'Xã Nhân Thắng', 'xã', 'Nhân Thắng', '24', 'Tỉnh Bắc Ninh'),
  ('09487', 'Xã Đông Cứu', 'xã', 'Đông Cứu', '24', 'Tỉnh Bắc Ninh'),
  ('09496', 'Xã Lương Tài', 'xã', 'Lương Tài', '24', 'Tỉnh Bắc Ninh'),
  ('09499', 'Xã Trung Kênh', 'xã', 'Trung Kênh', '24', 'Tỉnh Bắc Ninh'),
  ('09523', 'Xã Trung Chính', 'xã', 'Trung Chính', '24', 'Tỉnh Bắc Ninh'),
  ('09529', 'Xã Lâm Thao', 'xã', 'Lâm Thao', '24', 'Tỉnh Bắc Ninh'),
  ('12619', 'Xã Diên Hà', 'xã', 'Diên Hà', '33', 'Tỉnh Hưng Yên'),
  ('11953', 'Phường Phố Hiến', 'phường', 'Phố Hiến', '33', 'Tỉnh Hưng Yên'),
  ('11977', 'Xã Tân Hưng', 'xã', 'Tân Hưng', '33', 'Tỉnh Hưng Yên'),
  ('11980', 'Phường Hồng Châu', 'phường', 'Hồng Châu', '33', 'Tỉnh Hưng Yên'),
  ('11983', 'Phường Sơn Nam', 'phường', 'Sơn Nam', '33', 'Tỉnh Hưng Yên'),
  ('11992', 'Xã Lạc Đạo', 'xã', 'Lạc Đạo', '33', 'Tỉnh Hưng Yên'),
  ('11995', 'Xã Đại Đồng', 'xã', 'Đại Đồng', '33', 'Tỉnh Hưng Yên'),
  ('12004', 'Xã Như Quỳnh', 'xã', 'Như Quỳnh', '33', 'Tỉnh Hưng Yên'),
  ('12019', 'Xã Văn Giang', 'xã', 'Văn Giang', '33', 'Tỉnh Hưng Yên'),
  ('12025', 'Xã Phụng Công', 'xã', 'Phụng Công', '33', 'Tỉnh Hưng Yên'),
  ('12031', 'Xã Nghĩa Trụ', 'xã', 'Nghĩa Trụ', '33', 'Tỉnh Hưng Yên'),
  ('12049', 'Xã Mễ Sở', 'xã', 'Mễ Sở', '33', 'Tỉnh Hưng Yên'),
  ('12064', 'Xã Nguyễn Văn Linh', 'xã', 'Nguyễn Văn Linh', '33', 'Tỉnh Hưng Yên'),
  ('12070', 'Xã Hoàn Long', 'xã', 'Hoàn Long', '33', 'Tỉnh Hưng Yên'),
  ('12073', 'Xã Yên Mỹ', 'xã', 'Yên Mỹ', '33', 'Tỉnh Hưng Yên'),
  ('12091', 'Xã Việt Yên', 'xã', 'Việt Yên', '33', 'Tỉnh Hưng Yên'),
  ('12103', 'Phường Mỹ Hào', 'phường', 'Mỹ Hào', '33', 'Tỉnh Hưng Yên'),
  ('12127', 'Phường Thượng Hồng', 'phường', 'Thượng Hồng', '33', 'Tỉnh Hưng Yên'),
  ('12133', 'Phường Đường Hào', 'phường', 'Đường Hào', '33', 'Tỉnh Hưng Yên'),
  ('12142', 'Xã Ân Thi', 'xã', 'Ân Thi', '33', 'Tỉnh Hưng Yên'),
  ('12148', 'Xã Phạm Ngũ Lão', 'xã', 'Phạm Ngũ Lão', '33', 'Tỉnh Hưng Yên'),
  ('12166', 'Xã Xuân Trúc', 'xã', 'Xuân Trúc', '33', 'Tỉnh Hưng Yên'),
  ('12184', 'Xã Nguyễn Trãi', 'xã', 'Nguyễn Trãi', '33', 'Tỉnh Hưng Yên'),
  ('12196', 'Xã Hồng Quang', 'xã', 'Hồng Quang', '33', 'Tỉnh Hưng Yên'),
  ('12205', 'Xã Khoái Châu', 'xã', 'Khoái Châu', '33', 'Tỉnh Hưng Yên'),
  ('12223', 'Xã Triệu Việt Vương', 'xã', 'Triệu Việt Vương', '33', 'Tỉnh Hưng Yên'),
  ('12238', 'Xã Việt Tiến', 'xã', 'Việt Tiến', '33', 'Tỉnh Hưng Yên'),
  ('12247', 'Xã Châu Ninh', 'xã', 'Châu Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12271', 'Xã Chí Minh', 'xã', 'Chí Minh', '33', 'Tỉnh Hưng Yên'),
  ('12280', 'Xã Lương Bằng', 'xã', 'Lương Bằng', '33', 'Tỉnh Hưng Yên'),
  ('12286', 'Xã Nghĩa Dân', 'xã', 'Nghĩa Dân', '33', 'Tỉnh Hưng Yên'),
  ('12313', 'Xã Đức Hợp', 'xã', 'Đức Hợp', '33', 'Tỉnh Hưng Yên'),
  ('12322', 'Xã Hiệp Cường', 'xã', 'Hiệp Cường', '33', 'Tỉnh Hưng Yên'),
  ('12337', 'Xã Hoàng Hoa Thám', 'xã', 'Hoàng Hoa Thám', '33', 'Tỉnh Hưng Yên'),
  ('12361', 'Xã Tiên Hoa', 'xã', 'Tiên Hoa', '33', 'Tỉnh Hưng Yên'),
  ('12364', 'Xã Tiên Lữ', 'xã', 'Tiên Lữ', '33', 'Tỉnh Hưng Yên'),
  ('12391', 'Xã Quang Hưng', 'xã', 'Quang Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12406', 'Xã Đoàn Đào', 'xã', 'Đoàn Đào', '33', 'Tỉnh Hưng Yên'),
  ('12424', 'Xã Tiên Tiến', 'xã', 'Tiên Tiến', '33', 'Tỉnh Hưng Yên'),
  ('12427', 'Xã Tống Trân', 'xã', 'Tống Trân', '33', 'Tỉnh Hưng Yên'),
  ('12452', 'Phường Trần Hưng Đạo', 'phường', 'Trần Hưng Đạo', '33', 'Tỉnh Hưng Yên'),
  ('12454', 'Phường Trần Lãm', 'phường', 'Trần Lãm', '33', 'Tỉnh Hưng Yên'),
  ('12466', 'Phường Vũ Phúc', 'phường', 'Vũ Phúc', '33', 'Tỉnh Hưng Yên'),
  ('12472', 'Xã Quỳnh Phụ', 'xã', 'Quỳnh Phụ', '33', 'Tỉnh Hưng Yên'),
  ('12499', 'Xã A Sào', 'xã', 'A Sào', '33', 'Tỉnh Hưng Yên'),
  ('12511', 'Xã Minh Thọ', 'xã', 'Minh Thọ', '33', 'Tỉnh Hưng Yên'),
  ('12517', 'Xã Ngọc Lâm', 'xã', 'Ngọc Lâm', '33', 'Tỉnh Hưng Yên'),
  ('12523', 'Xã Phụ Dực', 'xã', 'Phụ Dực', '33', 'Tỉnh Hưng Yên'),
  ('12526', 'Xã Đồng Bằng', 'xã', 'Đồng Bằng', '33', 'Tỉnh Hưng Yên'),
  ('12532', 'Xã Nguyễn Du', 'xã', 'Nguyễn Du', '33', 'Tỉnh Hưng Yên'),
  ('12577', 'Xã Quỳnh An', 'xã', 'Quỳnh An', '33', 'Tỉnh Hưng Yên'),
  ('12583', 'Xã Tân Tiến', 'xã', 'Tân Tiến', '33', 'Tỉnh Hưng Yên'),
  ('12586', 'Xã Hưng Hà', 'xã', 'Hưng Hà', '33', 'Tỉnh Hưng Yên'),
  ('12595', 'Xã Ngự Thiên', 'xã', 'Ngự Thiên', '33', 'Tỉnh Hưng Yên'),
  ('12613', 'Xã Long Hưng', 'xã', 'Long Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12631', 'Xã Thần Khê', 'xã', 'Thần Khê', '33', 'Tỉnh Hưng Yên'),
  ('12634', 'Xã Tiên La', 'xã', 'Tiên La', '33', 'Tỉnh Hưng Yên'),
  ('12676', 'Xã Lê Quý Đôn', 'xã', 'Lê Quý Đôn', '33', 'Tỉnh Hưng Yên'),
  ('12685', 'Xã Hồng Minh', 'xã', 'Hồng Minh', '33', 'Tỉnh Hưng Yên'),
  ('12688', 'Xã Đông Hưng', 'xã', 'Đông Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12694', 'Xã Bắc Đông Hưng', 'xã', 'Bắc Đông Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12700', 'Xã Bắc Tiên Hưng', 'xã', 'Bắc Tiên Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12736', 'Xã Đông Tiên Hưng', 'xã', 'Đông Tiên Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12745', 'Xã Bắc Đông Quan', 'xã', 'Bắc Đông Quan', '33', 'Tỉnh Hưng Yên'),
  ('12754', 'Xã Tiên Hưng', 'xã', 'Tiên Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12763', 'Xã Nam Tiên Hưng', 'xã', 'Nam Tiên Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12775', 'Xã Nam Đông Hưng', 'xã', 'Nam Đông Hưng', '33', 'Tỉnh Hưng Yên'),
  ('12793', 'Xã Đông Quan', 'xã', 'Đông Quan', '33', 'Tỉnh Hưng Yên'),
  ('12817', 'Phường Trà Lý', 'phường', 'Trà Lý', '33', 'Tỉnh Hưng Yên'),
  ('12826', 'Xã Thái Thuỵ', 'xã', 'Thái Thuỵ', '33', 'Tỉnh Hưng Yên'),
  ('12850', 'Xã Tây Thuỵ Anh', 'xã', 'Tây Thuỵ Anh', '33', 'Tỉnh Hưng Yên'),
  ('12859', 'Xã Bắc Thuỵ Anh', 'xã', 'Bắc Thuỵ Anh', '33', 'Tỉnh Hưng Yên'),
  ('12862', 'Xã Đông Thuỵ Anh', 'xã', 'Đông Thuỵ Anh', '33', 'Tỉnh Hưng Yên'),
  ('12865', 'Xã Thuỵ Anh', 'xã', 'Thuỵ Anh', '33', 'Tỉnh Hưng Yên'),
  ('12904', 'Xã Nam Thuỵ Anh', 'xã', 'Nam Thuỵ Anh', '33', 'Tỉnh Hưng Yên'),
  ('12916', 'Xã Bắc Thái Ninh', 'xã', 'Bắc Thái Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12919', 'Xã Tây Thái Ninh', 'xã', 'Tây Thái Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12922', 'Xã Thái Ninh', 'xã', 'Thái Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12943', 'Xã Đông Thái Ninh', 'xã', 'Đông Thái Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12961', 'Xã Nam Thái Ninh', 'xã', 'Nam Thái Ninh', '33', 'Tỉnh Hưng Yên'),
  ('12970', 'Xã Tiền Hải', 'xã', 'Tiền Hải', '33', 'Tỉnh Hưng Yên'),
  ('12988', 'Xã Đông Tiền Hải', 'xã', 'Đông Tiền Hải', '33', 'Tỉnh Hưng Yên'),
  ('13003', 'Xã Đồng Châu', 'xã', 'Đồng Châu', '33', 'Tỉnh Hưng Yên'),
  ('13021', 'Xã Ái Quốc', 'xã', 'Ái Quốc', '33', 'Tỉnh Hưng Yên'),
  ('13039', 'Xã Tây Tiền Hải', 'xã', 'Tây Tiền Hải', '33', 'Tỉnh Hưng Yên'),
  ('13057', 'Xã Nam Cường', 'xã', 'Nam Cường', '33', 'Tỉnh Hưng Yên'),
  ('13063', 'Xã Nam Tiền Hải', 'xã', 'Nam Tiền Hải', '33', 'Tỉnh Hưng Yên'),
  ('13066', 'Xã Hưng Phú', 'xã', 'Hưng Phú', '33', 'Tỉnh Hưng Yên'),
  ('13075', 'Xã Kiến Xương', 'xã', 'Kiến Xương', '33', 'Tỉnh Hưng Yên'),
  ('13093', 'Xã Trà Giang', 'xã', 'Trà Giang', '33', 'Tỉnh Hưng Yên'),
  ('13096', 'Xã Bình Nguyên', 'xã', 'Bình Nguyên', '33', 'Tỉnh Hưng Yên'),
  ('13120', 'Xã Lê Lợi', 'xã', 'Lê Lợi', '33', 'Tỉnh Hưng Yên'),
  ('13132', 'Xã Quang Lịch', 'xã', 'Quang Lịch', '33', 'Tỉnh Hưng Yên'),
  ('13141', 'Xã Vũ Quý', 'xã', 'Vũ Quý', '33', 'Tỉnh Hưng Yên'),
  ('13159', 'Xã Hồng Vũ', 'xã', 'Hồng Vũ', '33', 'Tỉnh Hưng Yên'),
  ('13183', 'Xã Bình Thanh', 'xã', 'Bình Thanh', '33', 'Tỉnh Hưng Yên'),
  ('13186', 'Xã Bình Định', 'xã', 'Bình Định', '33', 'Tỉnh Hưng Yên'),
  ('13192', 'Xã Vũ Thư', 'xã', 'Vũ Thư', '33', 'Tỉnh Hưng Yên'),
  ('13219', 'Xã Vạn Xuân', 'xã', 'Vạn Xuân', '33', 'Tỉnh Hưng Yên'),
  ('13222', 'Xã Thư Trì', 'xã', 'Thư Trì', '33', 'Tỉnh Hưng Yên'),
  ('13225', 'Phường Thái Bình', 'phường', 'Thái Bình', '33', 'Tỉnh Hưng Yên'),
  ('13246', 'Xã Tân Thuận', 'xã', 'Tân Thuận', '33', 'Tỉnh Hưng Yên'),
  ('13264', 'Xã Thư Vũ', 'xã', 'Thư Vũ', '33', 'Tỉnh Hưng Yên'),
  ('13279', 'Xã Vũ Tiên', 'xã', 'Vũ Tiên', '33', 'Tỉnh Hưng Yên')
ON CONFLICT (ma_xa) DO UPDATE SET ten_xa=EXCLUDED.ten_xa, ten_xa_ngan=EXCLUDED.ten_xa_ngan;

