version: '3.8'

services:
  xangxe_app:
    build: .
    container_name: xangxe_web_server
    ports:
      - "80:8000"  # Ánh xạ cổng 80 công cộng của máy anh vào cổng 8000 của Flask
    volumes:
      - ./data:/app/data  # Đồng bộ thư mục hóa đơn từ máy vào Docker
    restart: always